# A. First introductive example using Python code : reading the known word 'choisir' in French

## 0. Summary
* 1- Default configuration
* 2- Default output
* 3- Getting specific result values
    * a. Visual and phonological attention
    * b. Probability distributions
    * c. Decisions taken by the model

## 1. Default configuration

It's possible to run a simulation without giving any parameter, because there are default parameters to configure the simulation.
Here are some example of the most important default configurations of model parameters.
How to configure the simulations will be explained at the end of this notebook.

* Language : French (langue="fr")
* Visuo-attentional parameters (Q=1, sd=1), classic visuo-attentional exploration of the stimulus
* Within context : 5 words in the context ($N_S=5$), 5 times more likely than the others ($p_S=5$)
* Word phonologically and orthographically familiar (remove_stim=False)
* Incidental learning is activated (learning=True)
* All top-down information flows are activated
* the prior (a priory) probability of a word is according to its log frequency (logFreq=True)
* comparisons with stimuli of length +1/-1 are enabled (shift=True)
* Orthographic neighbors of the stimulus are not removed (remove_neighbors=False)

As an example, see below the default configuration of the simu and braid classe. For complete information about all default parameters
for all classes, see the documentation.

```python
 sim = simu(model_param=None,
             ortho_param=None,
             phono_param=None,
             semantic_param=None,
             simu_args=None,
             level='simu',
             build_prototype=False,
             max_iter=1000,
             t_min=50,
             simu_type="H",
             thr_expo=0.1,
             stop_criterion_type= "pMean",
             pos_init=-1,
             serial_reading=False)


model = braid(ortho_param,
                phono_param,
                semantic_param,
                path='../',
                langue="fr",
                lexicon_name="",
                recalage=True,
                iteration_type = "reading" )
```


## 2. Running a simple simulation

In [1]:
## Imports
braidPath = "../"
import sys
sys.path.append(braidPath)
from braidpy.simu import simu

## Specific imports for printing
import numpy as np
np.set_printoptions(threshold=50)


## The simplest example possible
sim=simu()
sim.stim="chanter"
sim.run_simu_general()


max length = 8
max length = 7


SIMU:root:context words : []


mod : phono coupling_a : 0.7573621975590991, coupling_b : 0.4505811026362787
mod : ortho coupling_a : 0.7402617815647823, coupling_b : 2.221674635970171


SIMU:root:modalité visual
SIMU:root:stimulus chanter, S@te
SIMU:root:freq = 125.81
SIMU:root:lexical status ortho: known
SIMU:root:lexical status phono: known
SIMU:root:simulation duration : 372
SIMU:root:
 ORTHO : mot  reconnu
SIMU:root:percept ortho, chanter, [0.6285, 0.7717, 0.8964, 0.855, 0.9373, 0.7441, 0.9436]
SIMU:root:ld ortho 0.9845702834869248
SIMU:root: word ortho chanter, idx = 5531, wmax = 0.974691, 8521 words 
SIMU:root: : word_stim ortho None
SIMU:root:
 PHONO : mot  reconnu
SIMU:root:percept phono, S@te~~~~, [0.9347, 0.9486, 0.9341, 0.9424, 0.0692, 0.0303, 0.0303, 0.0303]
SIMU:root:ld phono 0.6124479477896416
SIMU:root: word phono S@te, idx = 5531, wmax = 0.979611, 8521 words 
SIMU:root: : word_stim phono None
SIMU:root:Psi score : 0.9999815504972789
SIMU:root:
 IDENTIFICATION
SIMU:root:chosen modality: ortho
SIMU:root:Identification ortho: /S@te/
SIMU:root:
 SUCCESS 
SIMU:root:Psi Ok
SIMU:root:WFusion Ok
SIMU:root:
 FIXATIONS
SIMU:root:fixation times: [0, 52, 319]
SIMU

## 2. Default output

When running the above simulation, there is a default output that gives most of the interesting informations about the simulation
(if you want to disable this default output, you should put level="expe" in the expe parameters explained below).
Here is a quick explanation of the results.

### All important information about the simulation results

* Words that belong to the context
* Stimulus name
* Simulation duration
* Distributions in the orthographic/phonological modalities
    * word recognized (categorized as known) or not
    * percept distribution (maximum of the probability distribution in each position)
    * lexical decision distribution (Yes value)
    * word distribution : its name, index, value, as well as the total number of words
    * word probability value for the stimulus
    * for phono only : similarity between the expected pronunciation and the calculated one (psi score)
* Final identification
    * chosen modality (modality where the word is being recognized with the most certainty)
    * chosen word
* Success
    * pronunciation error ? (Psi)
    * phono word identification error ? (WPhi)
    * final word identification error ? (WFusion)
* Fixations
    * times
    * positions
    * attentional dispersion values
    * phonological positions
    * phonological position errors (when considering the correct phonological position according to the graphemic segmentation)
* Used words for decoding
    * list of all words used during decoding, according to the position of visual attention
* Learning, in each modality:
    * Create or update new trace
    * Maximum values of the new distribution at each position
    * New frequency value



## 3. Getting specific result values

If you need more than just rapidly seeing the results, but needs precise information about the simulation, you can ask for it in only few lines of codes.
The probability distributions will generally be numpy arrays.


### a. Probability distributions

* Letter percept distribution is an array of size : len stimulus x len alphabet x simulation duration
* 1st Letter Percept distribution through time :

In [2]:
sim.res["ortho"]["percept"][0]

array([[0.02631579, 0.02630267, 0.02628947, ..., 0.00975996, 0.009582  ,
        0.0094049 ],
       [0.02631579, 0.02630504, 0.02629421, ..., 0.0099362 , 0.0097552 ,
        0.00957506],
       [0.02631579, 0.02630384, 0.02629182, ..., 0.0098414 , 0.00966205,
        0.00948355],
       ...,
       [0.02631579, 0.02630237, 0.02628889, ..., 0.00972676, 0.00954941,
        0.0093729 ],
       [0.02631579, 0.02630238, 0.0262889 , ..., 0.00972667, 0.00954932,
        0.00937281],
       [0.02631579, 0.02630236, 0.02628885, ..., 0.00972544, 0.0095481 ,
        0.00937162]])

* 1st Letter Percept distribution at the end of the simulation

In [3]:
sim.res["ortho"]["percept"][0][:,-1]

array([0.0094049 , 0.00957506, 0.00948355, 0.0096013 , 0.62846574,
       0.01589164, 0.00957448, 0.00994471, 0.00991766, 0.00960356,
       0.00946557, 0.00954924, 0.00937931, 0.00939917, 0.02163591,
       0.00937606, 0.00937337, 0.00937499, 0.00937518, 0.00939987,
       0.00939213, 0.00942006, 0.01082739, 0.01074564, 0.0096495 ,
       0.00946695, 0.00941517, 0.00938677, 0.00939458, 0.00939003,
       0.00945402, 0.00938964, 0.00941497, 0.00937233, 0.00937221,
       0.0093729 , 0.00937281, 0.00937162])

* Word distribution is an array of size : size lexicon x simulation duration
* Word distribution through time

In [4]:
sim.res["ortho"]["word"]

array([[1.75188300e-04, 1.74208163e-04, 1.73223554e-04, ...,
        8.21268039e-10, 7.96487600e-10, 7.72973998e-10],
       [8.92936576e-05, 8.87698826e-05, 8.82454703e-05, ...,
        6.30579443e-12, 5.96075769e-12, 5.63844623e-12],
       [5.08081268e-04, 5.05136992e-04, 5.02152506e-04, ...,
        2.91395530e-09, 2.80939306e-09, 2.71073347e-09],
       ...,
       [4.96158834e-05, 4.92728407e-05, 4.89294323e-05, ...,
        8.03766017e-11, 7.57382574e-11, 7.14150867e-11],
       [4.10818928e-05, 4.08987274e-05, 4.07142198e-05, ...,
        6.30473149e-10, 6.01027258e-10, 5.73489275e-10],
       [5.09741172e-05, 5.08293761e-05, 5.06822317e-05, ...,
        1.78576755e-11, 1.58836800e-11, 1.41367446e-11]])

* Word distribution at the end of the simulation

In [5]:
sim.res["ortho"]["word"][:,-1]

array([7.72973998e-10, 5.63844623e-12, 2.71073347e-09, ...,
       7.14150867e-11, 5.73489275e-10, 1.41367446e-11])

* Word distribution is an array of size : 2 x simulation duration
* Lexical decision distribution through time, Yes answer

In [6]:
sim.res["ortho"]["ld"][0]

array([0.5       , 0.50019757, 0.50053524, ..., 0.9842528 , 0.98441312,
       0.98457028])

* Lexical decision distribution at the end of the simulation, Yes answer

In [7]:
sim.res["ortho"]["ld"][:,-1]

array([0.98457028, 0.01542972])

### b. Visual and phonological attention

* all fixation infos in the visual or phonological modalities

In [8]:
print(sim.fix['ortho'])
print(sim.fix['phono'])


{'t': [0, 52, 319], 'att': [array([0.14496062, 0.15392448, 0.15703396, 0.15392448, 0.14496062,
       0.13116579, 0.11403006]), array([0.11403006, 0.13116579, 0.14496062, 0.15392448, 0.15703396,
       0.15392448, 0.14496062]), array([0.10022875, 0.11999561, 0.1380278 , 0.15254431, 0.16197712,
       0.16524928, 0.16197712])], 'pos': [2, 4, 5], 'sd': [5, 5, 5], 'err': []}
{'t': [], 'att': [array([0.00336133, 0.00365239, 0.00375491, 0.00365239, 0.00336133,
       0.00292685, 0.00241128, 0.00187953]), array([0.00280917, 0.00322617, 0.00350553, 0.00360393, 0.00350553,
       0.00322617, 0.00280917, 0.00231432]), array([0.00231432, 0.00280917, 0.00322617, 0.00350553, 0.00360393,
       0.00350553, 0.00322617, 0.00280917])], 'pos': [2, 3, 4], 'sd': [], 'err': []}


* visual fixation times

In [9]:
sim.fix['ortho']['t']


[0, 52, 319]

* visual attention distributions at each fixation

In [10]:
sim.fix['ortho']['att']

[array([0.14496062, 0.15392448, 0.15703396, 0.15392448, 0.14496062,
        0.13116579, 0.11403006]),
 array([0.11403006, 0.13116579, 0.14496062, 0.15392448, 0.15703396,
        0.15392448, 0.14496062]),
 array([0.10022875, 0.11999561, 0.1380278 , 0.15254431, 0.16197712,
        0.16524928, 0.16197712])]

* focus of visual attention at each fixation

In [11]:
sim.fix['ortho']['pos']

[2, 4, 5]

* dispersion of visual attention at each fixation

In [12]:
sim.fix['ortho']['sd']


[5, 5, 5]

### c. Decisions taken by the model
* Is the stimulus novel ?

In [13]:
sim.model.PM

False

* What are the most likely letters ?

In [14]:
sim.model.ortho.percept.decision()

'chanter'

* What are the most likely phonemes ?

In [15]:
sim.model.phono.percept.decision()

'S@te~~~~'

* What is the most likely word in the visual modality ?

In [16]:
sim.model.ortho.word.decision('word')

'chanter'

* What is the most likely word in the phonological modality ?

In [17]:
sim.model.phono.word.decision('word')

'S@te'

* What is the most likely word all modalities considered ?

In [18]:
sim.model.chosen_word

# B. Second introductive example : configuration of the simulation

You can configurate many aspects of the simulation, more precisely:
* parameters of the simulation, to define what the task is
* parameters of the model, to define how processing during one iteration works
* parameters of the ortho/phono modality, again to define how processing works during one iteration,
    but with aspects that are specific to each modality
* parameters of the semantic branch of the model, to define how context works

To define that, you must define dictionaries of parameters, with keys as the name of the parameters, and values as the chosen values for the parameter.
* All attributes can be found in the documentation of the classes
* In the code, each modality has inner classes corresponding to the different submodels (sensor, percept, word, lexical, attention).
All parameters of the inner classes of ortho and phono must be given in the corresponding modality (ortho_param or phono_param).
This is done this way to avoid model definition with too many dictionaries (ortho_sensor_param, phono_sensor_param etc.).

* The attributes listed below for our simulation are (list is non-exhaustive):
    * simu attributes
        * max_iter : maximum simulation duration
        * t_min : minimum duration of a fixation
        * simu_type : type of simulation (one central fixation, entropy-based visual exploration (H)..)
        * thr_expo : letter entropy necessary to end the simulation (in % of the initial entropy)
        * stop_criterion_type : criterion to stop the simulation
        * serial_reading : boolean to indicate if the simulation follows a serial reading mode or not
    * model attributes
        * langue : language, can be French, English or German
        * path: the path to the project root
    * ortho attributes
        * stim : the stimulus to be read
        * learning : boolean, learning at the end of the simulation ?
        * remove_stim : boolean, stimulus removed from the lexicon in this modality ?
        * sd : attentional dispersion
        * Q : attentional quantity
    * semantic attributes :
        * context_sem : boolean, is the simulation within context ?
        * p_sem : the strength of context
        * N_sem : the size of context

* Only the attributes that differ from the default attributes need to be given during simulation init (see the class documentation to get all default values).

In [19]:
simu_param={"max_iter":2000, "t_min":50, "simu_type":"H", "thr_expo":0.1, "stop_criterion_type":"pMean", "serial_reading":False}
model_param={"langue":"fr", "path":braidPath}
ortho_param = {"stim":"partir","learning":True, "remove_stim":True,"sd":1, 'Q':1}
phono_param = {"learning":True, "remove_stim":False}
semantic_param = {"context_sem":False}
simu_args = {}
sim = simu(model_param, ortho_param, phono_param, simu_args, **simu_param)
sim.run_simu_general()


max length = 8


SIMU:root:context words : []


max length = 7
mod : phono coupling_a : 0.7573621975590991, coupling_b : 0.4505811026362787
mod : ortho coupling_a : 0.7402617815647823, coupling_b : 2.221674635970171


SIMU:root:modalité visual
SIMU:root:stimulus partir, paRtiR
SIMU:root:freq = 0.0
SIMU:root:lexical status ortho: novel
SIMU:root:lexical status phono: known
SIMU:root:simulation duration : 2000
SIMU:root:
 ORTHO : mot  reconnu
SIMU:root:percept ortho, partir~, [0.8908, 0.9336, 0.9485, 0.9515, 0.9381, 0.9691, 0.0268]
SIMU:root:ld ortho 0.10574035104046105
SIMU:root: word ortho parti, idx = 2687, wmax = 0.789603, 8521 words 
SIMU:root: : word_stim ortho None
SIMU:root:
 PHONO : mot  reconnu
SIMU:root:percept phono, paRti~~~, [0.9711, 0.9785, 0.981, 0.9797, 0.9826, 0.0423, 0.0313, 0.0303]
SIMU:root:ld phono 0.883148407824685
SIMU:root: word phono paRtiR, idx = 5289, wmax = 0.438577, 8521 words 
SIMU:root: : word_stim phono None
SIMU:root:Psi score : 0.8747077098966649
SIMU:root:
 IDENTIFICATION
SIMU:root:chosen modality: phono
SIMU:root:Identification phono: /paRtiR/
SIMU:root:
 SUCCESS 
SIMU:root:Erreur WPhi: None
SIMU:root:WFusion Ok
SIMU:root:
 FIXATIONS
SIMU:root:fixation times: [0, 5

### Specific case : specifying the position of the first fixation

for each type of simulation you can choose the initial position or let the model compute it automatically.
To choose the position, you directly sets the position (between 0 and len(stim)-1) before the simulation with :
```python
model.pos=pos
```
If no positon has been set (it's value remains -1), it will be calculated automatically by the model.
The position is set to -1 at the end of a simulation.

## Visualization

To visualize results, we recommand using the command-line with the option -g (see the notebook command_line.ipynb).
If you want to see plots using Python code anyway, you can use this code in a python file (not in a ipynb file), it will open a window with several interesting plots.

```python
braidPath = "../"
import sys
sys.path.append(braidPath)
from braidpy.simu import simu
from braidpy.GUI.gui import gui
from tornado.ioloop import IOLoop
from bokeh.server.server import Server
from bokeh.application import Application
from bokeh.application.handlers.function import FunctionHandler
sim=simu()
def modify_doc(doc):
    GUI = gui(sim)
    for att in dir(doc):
        try:
            setattr(doc,att,getattr(GUI.curdoc,att))
        except:
            pass
# Créez une instance de l'application Bokeh en utilisant la fonction de rappel
io_loop = IOLoop.current()
# Créez une instance du serveur Bokeh avec l'application Bokeh
server = Server(applications={'/': Application(FunctionHandler(modify_doc))}, io_loop=io_loop, port=5002)
server.start()
server.show('/')
io_loop.start()

```